apiVersion: apps/v1
kind: Deployment
metadata:
  name: twtr-be
spec:
  selector:
    matchLabels:
      app: twtr-be
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/path: "/status/format/prometheus"
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
      labels:
        app: twtr-be
    spec:
      containers:
      - name: twtr-be
        image: "somanwita/twtr-be"
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 1
          requests:
            cpu: 0.2
---
apiVersion: v1
kind: Service
metadata:
  name: twtr-be
  labels:
    app: twtr-be
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: twtr-be